version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      # echo "Running tests..."
      # Add your test command here, if applicable
  post_build:
    commands:
      - echo "Build completed, deploying to AWS Elastic Beanstalk (or your deployment destination)..."
      # Add your deployment commands here, such as deploying to Elastic Beanstalk, AWS Lambda, etc.
      # Example deployment to Elastic Beanstalk:
      # - aws elasticbeanstalk create-application-version --application-name your-app-name --version-label v1 --source-bundle S3Bucket=your-bucket,S3Key=your-key
      # - aws elasticbeanstalk update-environment --environment-name your-env-name --version-label v1
